var snowsrc="https://raw.githubusercontent.com/shahriaribnealam/cdn/refs/heads/main/js/background-effects/b1.png";
var snowsrc2="https://raw.githubusercontent.com/shahriaribnealam/cdn/refs/heads/main/js/background-effects/b2.png";
var snowsrc3="https://raw.githubusercontent.com/shahriaribnealam/cdn/refs/heads/main/js/background-effects/b3.png";
var snowsrc4="https://raw.githubusercontent.com/shahriaribnealam/cdn/refs/heads/main/js/background-effects/b4.png";
var snowsrc5="https://raw.githubusercontent.com/shahriaribnealam/cdn/refs/heads/main/js/background-effects/b5.png";
var snowsrc6="https://raw.githubusercontent.com/shahriaribnealam/cdn/refs/heads/main/js/background-effects/b6.png";
var snowsrc7="https://raw.githubusercontent.com/shahriaribnealam/cdn/refs/heads/main/js/background-effects/b8.png";
var snowsrc8="https://raw.githubusercontent.com/shahriaribnealam/cdn/refs/heads/main/js/background-effects/b1.png";
var snowsrc9="https://raw.githubusercontent.com/shahriaribnealam/cdn/refs/heads/main/js/background-effects/b2.png";
var snowsrc10="https://raw.githubusercontent.com/shahriaribnealam/cdn/refs/heads/main/js/background-effects/b3.png";
var no=10;var hidesnowtime=0;var snowdistance="pageheight";var ie4up=(document.all)?1:0;var ns6up=(document.getElementById&&!document.all)?1:0;function iecompattest(){return(document.compatMode&&document.compatMode!="BackCompat")?document.documentElement:document.body}
var dx,xp,yp;var am,stx,sty;var i,doc_width=800,doc_height=600;if(ns6up){doc_width=self.innerWidth;doc_height=self.innerHeight;}else if(ie4up){doc_width=iecompattest().clientWidth;doc_height=iecompattest().clientHeight;}
dx=new Array();xp=new Array();yp=new Array();am=new Array();stx=new Array();sty=new Array();snowsrc=(snowsrc.indexOf("dynamicdrive.com")!=-1)?"snow.gif":snowsrc
for(i=0;i<no;++i){dx[i]=0;xp[i]=Math.random()*(doc_width-50);yp[i]=Math.random()*doc_height;am[i]=Math.random()*20;stx[i]=0.02+Math.random()/10;sty[i]=0.7+Math.random();if(ie4up||ns6up){if(i==0){document.write("<div id=\"dot"+i+"\" style=\"POSITION: absolute; Z-INDEX: "+i+"; VISIBILITY: visible; TOP: 15px; LEFT: 15px;\"><img src='"+snowsrc+"' border=\"0\"><\/div>");}else if(i==1){document.write("<div id=\"dot"+i+"\" style=\"POSITION: absolute; Z-INDEX: "+i+"; VISIBILITY: visible; TOP: 15px; LEFT: 15px;\"><img src='"+snowsrc2+"' border=\"0\"><\/div>");}else if(i==2){document.write("<div id=\"dot"+i+"\" style=\"POSITION: absolute; Z-INDEX: "+i+"; VISIBILITY: visible; TOP: 15px; LEFT: 15px;\"><img src='"+snowsrc3+"' border=\"0\"><\/div>");}else if(i==3){document.write("<div id=\"dot"+i+"\" style=\"POSITION: absolute; Z-INDEX: "+i+"; VISIBILITY: visible; TOP: 15px; LEFT: 15px;\"><img src='"+snowsrc4+"' border=\"0\"><\/div>");}else if(i==4){document.write("<div id=\"dot"+i+"\" style=\"POSITION: absolute; Z-INDEX: "+i+"; VISIBILITY: visible; TOP: 15px; LEFT: 15px;\"><img src='"+snowsrc5+"' border=\"0\"><\/div>");}else if(i==5){document.write("<div id=\"dot"+i+"\" style=\"POSITION: absolute; Z-INDEX: "+i+"; VISIBILITY: visible; TOP: 15px; LEFT: 15px;\"><img src='"+snowsrc6+"' border=\"0\"><\/div>");}else if(i==6){document.write("<div id=\"dot"+i+"\" style=\"POSITION: absolute; Z-INDEX: "+i+"; VISIBILITY: visible; TOP: 15px; LEFT: 15px;\"><img src='"+snowsrc7+"' border=\"0\"><\/div>");}else if(i==7){document.write("<div id=\"dot"+i+"\" style=\"POSITION: absolute; Z-INDEX: "+i+"; VISIBILITY: visible; TOP: 15px; LEFT: 15px;\"><img src='"+snowsrc8+"' border=\"0\"><\/div>");}else if(i==8){document.write("<div id=\"dot"+i+"\" style=\"POSITION: absolute; Z-INDEX: "+i+"; VISIBILITY: visible; TOP: 15px; LEFT: 15px;\"><img src='"+snowsrc9+"' border=\"0\"><\/div>");}else{document.write("<div id=\"dot"+i+"\" style=\"POSITION: absolute; Z-INDEX: "+i+"; VISIBILITY: visible; TOP: 15px; LEFT: 15px;\"><img src='"+snowsrc10+"' border=\"0\"><\/div>");}}}
function snowIE_NS6(){doc_width=ns6up?window.innerWidth-10:iecompattest().clientWidth-10;doc_height=(window.innerHeight&&snowdistance=="windowheight")?window.innerHeight:(ie4up&&snowdistance=="windowheight")?iecompattest().clientHeight:(ie4up&&!window.opera&&snowdistance=="pageheight")?iecompattest().scrollHeight:iecompattest().offsetHeight;for(i=0;i<no;++i){yp[i]+=sty[i];if(yp[i]>doc_height-50){xp[i]=Math.random()*(doc_width-am[i]-30);yp[i]=0;stx[i]=0.02+Math.random()/10;sty[i]=0.7+Math.random();}
dx[i]+=stx[i];document.getElementById("dot"+i).style.top=yp[i]+"px";document.getElementById("dot"+i).style.left=xp[i]+am[i]*Math.sin(dx[i])+"px";}
snowtimer=setTimeout("snowIE_NS6()",10);}
function hidesnow(){if(window.snowtimer)clearTimeout(snowtimer)
for(i=0;i<no;i++)document.getElementById("dot"+i).style.visibility="hidden"}
if(ie4up||ns6up){snowIE_NS6();if(hidesnowtime>0)
setTimeout("hidesnow()",hidesnowtime*1000)};